### ISSUE TITLE
Mamehub is using full path again

### ISSUE THREAD

**Issue by Prinygod** [MisterTea/MAMEHub#137]
since the latest update, mess games are being launched with fullpath instead of shortname. this causes certain games not to work. i.e. all nes and snes dsp game.

**Comment by Gitweazle** [comment]
Found out why Amiga games are no longer working. The last person that worked on Amiga forgot to link it to the correct softwarelist name (amigaocs_flop).

So now (still as of 0.163b) the shortname method will not work for Amiga, only full path.

This back n forth between shortname/fullpath due to bugs and inconsistencies is annoying. So I would suggest MAMEHub does the same as RetroArch:

Have an option in settings to switch between the 2 methods.
