### ISSUE TITLE
Problems with new CSUME (01-07-2015)

### ISSUE THREAD

**Issue by Gitweazle** [MisterTea/MAMEHub#315]
I have the following problems with the new version, in single player too:

- Starting, closing and connecting to a game are much slower than usual.
- The screen freezes, audio continues. When I task out ALT+TAB and back the video frame changes once in a while. This is both with rollback ON or OFF, it's worse when it is ON though.
- Less demanding games seem to work better, but the screen still stutters online (with rollback OFF).
- It seems a little faster when I use command line.

**Comment by MisterTea** [comment]
I'm not sure why starting would be slower, but I'll look into it.

I changed the code to stop rendering frames when you fall behind where you should be in terms of the frame rate.  This is because it is impossible to catch up on certain OS's (like osx & linux) if you render every frame.  If you are dropping frames, it means you need to get a faster cpu.  Rollback will use the CPU more heavily so it makes sense that you are dropping more frames with rollback enabled.

Can you ask the MAME/MESS/UME team if there are any optimization flags they use?  I notice in the code there are some flags (like MAXOPT) which should make CSUME faster, but Im' hesitant to try them without blessing from the core team.

**Comment by Gitweazle** [comment]
I asked on the MESS board in the compile thread.
Answer: *There are no optimization flags, everything is pre-tuned to be as good as it gets.*

All games seem to be working fine again except... Midway games. 
Before I only experienced slowdown to 50%, but now frames are not updating at all. I can hear the sound in the background.
I seem to be the only one experiencing this. Maybe it's my old graphics card.
- Why only Midway?
- Why does it work fine in MAMEHub3.0 and official MAME/UME? (copied over UME.ini from MH to UME)

PS: The slowdown during starting/closing/connecting happened just before the server crash. I believe that was the cause.

**Comment by Jaku2k** [comment]
Im having problem with any game that cant keep a solid 100% speed. A small hic-up and it all goes to hell. The screen freezes, uses a full cpu and by the time it manages to recover I see the title screen. Slower games dont work at all, I often need to kill it.

Otherwise everything is running much faster than before, 2x increase in performance I would say.
Good work.

**Comment by MisterTea** [comment]
@Jaku2k Please send me a log where this happens, and also tell me which rom it is.

**Comment by Gitweazle** [comment]
This makes sense. Since Midway runs slow for me, for whatever reason, it runs far below 100% which is causing the screen to freeze.
Emulation seems to keep running in the background as I can hear sounds and it reacts to my key presses. It's just the video frames that are stuck.

I am also experiencing slight video stuttering in most games, while the sound is excellent. Connections also seem extremely stable; very nice.

**Comment by MisterTea** [comment]
9912692d4a8ad628e79c7531e914eb4d08ef0d47 should address this.  Please test and let me know.

**Comment by Jaku2k** [comment]
"Im having problem with any game that cant keep a solid 100% speed."
from good to worse:
http://pastebin.com/DZ0Cq2zz - Strider Hiryu 2 [shiryu2.zip] 
http://pastebin.com/WdCsZ2Dx - Deathsmiles [deathsml.zip]
http://pastebin.com/eGyN43sz - Columns '97 [colmns97.zip]

**Comment by Prinygod** [comment]
This should be fix now please create a new issue if you have any more problems
