### ISSUE TITLE
can't compile mamehub (to add autofire from mameuifx)

### ISSUE THREAD

**Issue by beeion** [MisterTea/MAMEHub#396]
i want to use autofire on mamehub.
but there isn't autofire option so i need to compile this mamehub from mameuifx 0.170

however due to the hard to understand with only word, and other problem is
[MINGW64] C:\Users\myfolder\Downloads\msys64\src>make -j8 NOWERROR=1 TARGET=ume
make: *** No targets specified and no makefile found.  Stop.

this one happen. looks like missed something but what is it then? is there someone to instruct compile more easily?

**Comment by Rocksteady18** [comment]
No need to recompile, name supports autofire for the past two years. It's in the cheat menu. Mamehub and mameuifx are dead.

https://github.com/mamedev/mame/pull/618

**Comment by beeion** [comment]
maybe you are right. 
but what am i wanted is how to compile mamehub. not what your write.

anyway do you know how to do it?

**Comment by Rocksteady18** [comment]
![image of xibit](http://i.qkme.me/363a6t.jpg)

**Comment by beeion** [comment]
maybe i am expecting you too much.

**Comment by MisterTea** [comment]
I'm porting mamehub forward to the latest mame and then I will update the compile instructions. If you want to help, please join out new discord (there's a link in the mamehub subreddit)

**Comment by beeion** [comment]
If you update compile instruction i hope more easy example will be added.

(Still not much know about how to use command prompt)

**Comment by beeion** [comment]
Hope to making more easy example. I don’t much know about how to use command prompt.

chdman.exe createcd -i "path & name of an ISO or CUE image of the CDROM" -o "path & name of the output CHD" 

With only these i can't understand how to use it.

example to create hell fire s.Chd: "Open Cmd and input "chdman.exe createcd -i "hell fire s.cue" -o "hell fire s.chd" 

Caution!: In text editor, cue binary must match with name of bin file exactly or it can’t create chd.

Maybe this would making easier to understand?

**Comment by Rocksteady18** [comment]
@Jason, thank you!  Love mamehub, longtime user here, had one of the first registered on your old proboard.

@beeno, stop. No one held my hand to learn these simple tasks. If you don't understand a word look it up. You do expect too much from me since you talk to me like I'm your butler. I can tell you right now your environment is never going to work.   Mingw and cygwin suck. The first error you post says there's no makefile in the text you post in here, do you know what a makefile is is there one actually in the source tree, you need to Google this stuff if you don't understand.  Get Linux and learn to read, in my opinion.  Github is not a concierge.

**Comment by MisterTea** [comment]
@rocksteady18 please join the discord and message me on there.

**Comment by beeion** [comment]
i guess there is no need to compile mame right now. 
new mame sdlmame64 has autofire in cheat menu.
it's not current mamehubclient but i'm end this issue
